# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  EasyUI_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  EasyUI_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := EasyUI Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

EasyUI:
ifneq (,$(EasyUI_config))
	@echo "==== Building EasyUI ($(EasyUI_config)) ===="
	@${MAKE} --no-print-directory -C EasyUI -f Makefile config=$(EasyUI_config)
endif

Sandbox: EasyUI
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C EasyUI -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   EasyUI"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"